name: Creates a comment on a new opened issue

on:
  issues:
    types: [opened]

jobs:
  print-token:
    permissions: write-all
    name: print-token
    environment: dev
    # needs: pre-pkr
    runs-on: ubuntu-24.04
    
  comments_with_action:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write    
    steps:
      - name: "dump github context"
        run: echo '${{toJSON(github.event)}}' | jq
        shell: bash

      - name: Create Comment
        uses: KeisukeYamashita/create-comment@v1
        with:
          number: 1
          comment: Comment for Issue or GitHub Pull Request    
